<?php

/**
 * @file
 * rt ajax autocomplete test
 */


/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function smiggy_help($path, $arg) {
  switch ($path) {
    case "admin/help#smiggy":
      return '<p>' . t("Smiggy") . '</p>';
      break;
  }
} 

/*rt add block to module
*/

function smiggy_block_info() {
  $blocks['smiggy'] = array(
    // The name that will appear in the block list.
    'info' => t('Smiggy block'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/*rt get some info
*/
function smiggy_contents(){
  //Get today's date.
  $today = getdate();
  //Calculate the date a week ago.
  $stasmiggy_time = mktime(0, 0, 0,$today['mon'],($today['mday'] - 7), $today['year']);
  //Get all posts from one week ago to the present.
  $end_time = time();
   //Use Database API to retrieve current posts.
  $query = db_select('node', 'n')
    ->fields('n', array('nid', 'title', 'created'))
    ->condition('status', 1) //Published.
    ->condition('created', array($stasmiggy_time, $end_time), 'BETWEEN')
    //rt I changed this from create to title
    ->orderBy('title', 'ASC') //Most recent first.
    ->execute(); 
  return $query;  
}

/*rt show the got info
*/

/**
 * Implements hook_block_view().
 * 
 * Prepares the contents of the block.
 */
function smiggy_block_view($delta = '') {
  switch ($delta) {
    case 'smiggy':
      $block['subject'] = t('Smiggy autocomplete add, I would rather expose the view');
      if (user_access('access content')) {
        // Use our custom function to retrieve data.
        $result = smiggy_contents();
        // Array to contain items for the block to render.
        $items = array();
        // Iterate over the resultset and format as links.
        foreach ($result as $node) {
          $items[] = array(
            'data' => l($node->title, 'node/' . $node->nid),
          ); 
        }
       // No content in the last week.
        if (empty($items)) {
          $block['content'] = t('Smiggy news available.');  
        } 
        else {
          // Pass data through theme function.
          $block['content'] = theme('item_list', array(
            'items' => $items));
        }
      }
    return $block;
  }
  
}